name: build and deploy the demo

on:
  push:
    branches: [ master ]
 
 
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout repo
          uses: actions/checkout@v1
          with:
            submodules: true

        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.8'
            architecture: 'x64'

        - name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r ./requirements.txt
            python3 -m pip install .
      
        - name: Sphinx Build
          run: cd demo && make html

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./demo/_build/html/

        
